(SIMP-9720) Fix sssd hooks
simp/pupmod-simp-simp_nfs pull request #49
Opened 2021-06-02 21:39 UTC by trevor-vaughan

* Ensure that the type of LDAP server is specified

SIMP-9720 #close

2021-06-10 12:33 UTC, jeannegreulich reviewed
In the tests that are failing it appears that in fips mode the el8 server cannot connect to the LDAP server to get a list of users and therefor does not create the home directory to mount.  Still trying to figure out what needs to be set to get it working.

2021-06-10 20:07 UTC, jeannegreulich commented
Ok, so default openssl policy in el8 for FIPS mode has only TLSv1_3 ciphers.  el7 openssl can't use TLS1_3 because it is not available in the version of openssl.  We dont' want to edit the FIPS policy on el8 and we can't add the ciphers to el7.  

There is something called min_version but it doesn't seem to override the cipher suite, it may just exclude ciphers if you have older ones in the cipher suites.

For some reason if you pass tls_options to net::ldap it is enabling SSL verification in openssl and the ca certs are not loaded into the system certificate store so you have to tell it where the ca cert path is.

conn_opts[:encryption] = { :method =>:start_tls, :tls_options => { :ciphers => ciphers_list, :ca_path => '/etc/pki/simp-testing/pki/cacerts' }}  seems to work.

2021-06-16 14:07 UTC, trevor-vaughan commented
@jeannegreulich Thanks for the updates, these look good to me!

2021-06-16 14:20 UTC, lnemsick-simp requested changes
docs update

2021-06-16 14:20 UTC, lnemsick-simp commented on manifests/create_home_dirs.pp
> +  Variant[Enum['simp'],Boolean]  $pki                     = simplib::lookup('simp_options::pki', { 'default_value' => false }),
Please update the CHANGELOG and REFERENCE.md for the new class parameters

2021-06-16 14:21 UTC, lnemsick-simp commented on .gitlab-ci.yml
>  # ==============================================================================
Puppet 5 removal should be noted in the changelog

2021-06-17 13:02 UTC, lnemsick-simp approved these changes

2021-06-17 13:03 UTC, lnemsick-simp approved these changes

2021-06-17 13:04 UTC, merged